POST http://localhost:9000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImxvZ2luIjoibWljaGFsMTIzYSIsImlhdCI6MTcxMDI0ODQzNn0.cfzYUDNlHggAWxT88cZk_6k7gQz_UxlV72xVWkrDQMw

{
    "description": "Start a task in progress",
    "due": "2023-04-04T05:00:00Z",
    "status": "in progress"
}

###

GET http://localhost:9000/users

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "login": "michal123a",
    "password": "notanadmin"
}

###

POST http://localhost:9000/login
Content-Type: application/json

{
    "login": "michal123a",
    "password": "notanadmin"
}

###

GET http://localhost:9000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImxvZ2luIjoibWljaGFsMTIzYSIsImlhdCI6MTcxMDI0ODQzNn0.cfzYUDNlHggAWxT88cZk_6k7gQz_UxlV72xVWkrDQMw