GET http://localhost:9000/tasks

###

POST http://localhost:9000/tasks
Content-Type: application/json

{
    "description": "Start a new career",
    "due": "2024-04-04T05:00:00Z",
    "status": "planned"
}

###

GET http://localhost:9000/users

###

POST http://localhost:9000/users
Content-Type: application/json

{
    "login": "user123a",
    "password": "admin1234"
}

###

POST http://localhost:9000/login
Content-Type: application/json

{
    "login": "user123a",
    "password": "admin1234"
}